// <auto-generated />
using System;
using KorisnikSistema.Data1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KorisnikSistema.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KorisnikSistema.Models.KorisniciSistema", b =>
                {
                    b.Property<int>("KorisnikSistemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikSistemaID"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikSistemaID");

                    b.ToTable("KorisniciSistemas");
                });

            modelBuilder.Entity("KorisnikSistema.Models.TipKorisnika", b =>
                {
                    b.Property<int>("TipKorisnikaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipKorisnikaID"));

                    b.Property<int?>("KorisniciSistemaKorisnikSistemaID")
                        .HasColumnType("int");

                    b.Property<string>("NazivTipaKorisnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipKorisnikaID");

                    b.HasIndex("KorisniciSistemaKorisnikSistemaID");

                    b.ToTable("TipKorisnikas");
                });

            modelBuilder.Entity("KorisnikSistema.Models.TipKorisnika", b =>
                {
                    b.HasOne("KorisnikSistema.Models.KorisniciSistema", null)
                        .WithMany("ListaTipovaKorisnika")
                        .HasForeignKey("KorisniciSistemaKorisnikSistemaID");
                });

            modelBuilder.Entity("KorisnikSistema.Models.KorisniciSistema", b =>
                {
                    b.Navigation("ListaTipovaKorisnika");
                });
#pragma warning restore 612, 618
        }
    }
}
