// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZasticenaZonaMikroservis.DataContext;

#nullable disable

namespace ZasticenaZonaMikroservis.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230218185013_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZasticenaZonaMikroservis.Models.ZasticenaZona", b =>
                {
                    b.Property<int>("ZasticenaZonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZasticenaZonaID"), 1L, 1);

                    b.Property<string>("DozvoljeniRadovi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepenZastite")
                        .HasColumnType("int");

                    b.Property<string>("VrstaZasticenogPodrucja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZasticenaZonaID");

                    b.ToTable("ZasticeneZone");

                    b.HasData(
                        new
                        {
                            ZasticenaZonaID = 5,
                            DozvoljeniRadovi = "uredjivanje staza",
                            StepenZastite = 5,
                            VrstaZasticenogPodrucja = "Nacionalni park"
                        },
                        new
                        {
                            ZasticenaZonaID = 13,
                            DozvoljeniRadovi = "kopanje",
                            StepenZastite = 3,
                            VrstaZasticenogPodrucja = "rezervat"
                        },
                        new
                        {
                            ZasticenaZonaID = 15,
                            DozvoljeniRadovi = "kopanje, asfaltiranje",
                            StepenZastite = 4,
                            VrstaZasticenogPodrucja = "arheolosko naselje"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
