// <auto-generated />
using System;
using JavnoNadPavle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JavnoNadPavle.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230218193421_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JavnoNadPavle.Models.Etapa", b =>
                {
                    b.Property<int>("EtapaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtapaID"));

                    b.Property<int>("Atr")
                        .HasColumnType("int");

                    b.HasKey("EtapaID");

                    b.ToTable("Etape");
                });

            modelBuilder.Entity("JavnoNadPavle.Models.JavnoNadmetanje", b =>
                {
                    b.Property<int>("JavnoNadmetanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JavnoNadmetanjeID"));

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<int>("EtapaID")
                        .HasColumnType("int");

                    b.Property<int>("IzlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<int>("NadmetanjeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisinaDopuneDepozita")
                        .HasColumnType("int");

                    b.HasKey("JavnoNadmetanjeID");

                    b.HasIndex("EtapaID");

                    b.HasIndex("NadmetanjeID");

                    b.ToTable("JavnaNadmetanja");
                });

            modelBuilder.Entity("JavnoNadPavle.Models.Nadmetanje", b =>
                {
                    b.Property<int>("NadmetanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NadmetanjeID"));

                    b.Property<int>("CenaPoHektaru")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.HasKey("NadmetanjeID");

                    b.ToTable("Nadmetanja");
                });

            modelBuilder.Entity("JavnoNadPavle.Models.JavnoNadmetanje", b =>
                {
                    b.HasOne("JavnoNadPavle.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavnoNadPavle.Models.Nadmetanje", "Nadmetanje")
                        .WithMany()
                        .HasForeignKey("NadmetanjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Nadmetanje");
                });
#pragma warning restore 612, 618
        }
    }
}
