// <auto-generated />
using KatastarskaOpstina_MikroservisiProjekat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KatastarskaOpstina_MikroservisiProjekat.Migrations
{
    [DbContext(typeof(KatastarskaOpstinaContext))]
    [Migration("20230218191540_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KatastarskaOpstina_MikroservisiProjekat.Models.KatastarskaOpstina", b =>
                {
                    b.Property<int>("katastarskaOpstinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("katastarskaOpstinaId"));

                    b.Property<string>("katastarskaOpstinaNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("katastarskaOpstinaId");

                    b.ToTable("katastarskaOpstina");

                    b.HasData(
                        new
                        {
                            katastarskaOpstinaId = 1,
                            katastarskaOpstinaNaziv = "Lipovac"
                        },
                        new
                        {
                            katastarskaOpstinaId = 2,
                            katastarskaOpstinaNaziv = "Brus"
                        },
                        new
                        {
                            katastarskaOpstinaId = 3,
                            katastarskaOpstinaNaziv = "Odzaci"
                        });
                });

            modelBuilder.Entity("KatastarskaOpstina_MikroservisiProjekat.Models.StatutOpstine", b =>
                {
                    b.Property<int>("statutOpstineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statutOpstineID"));

                    b.Property<string>("clan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("katastarskaOpstinaID")
                        .HasColumnType("int");

                    b.Property<string>("stav")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tacka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statutOpstineID");

                    b.HasIndex("katastarskaOpstinaID");

                    b.ToTable("statutOpstine");

                    b.HasData(
                        new
                        {
                            statutOpstineID = 4,
                            clan = "prvi",
                            katastarskaOpstinaID = 1,
                            stav = "11",
                            tacka = "1"
                        },
                        new
                        {
                            statutOpstineID = 5,
                            clan = "drugi",
                            katastarskaOpstinaID = 2,
                            stav = "12",
                            tacka = "2"
                        },
                        new
                        {
                            statutOpstineID = 6,
                            clan = "treci",
                            katastarskaOpstinaID = 3,
                            stav = "13",
                            tacka = "3"
                        });
                });

            modelBuilder.Entity("KatastarskaOpstina_MikroservisiProjekat.Models.StatutOpstine", b =>
                {
                    b.HasOne("KatastarskaOpstina_MikroservisiProjekat.Models.KatastarskaOpstina", "katastarskaOpstina")
                        .WithMany()
                        .HasForeignKey("katastarskaOpstinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("katastarskaOpstina");
                });
#pragma warning restore 612, 618
        }
    }
}
