name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"URIS-2022_Tim-5---URUS---NewDevProject" /o:"uris-2022" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet publish Andjela/Kupac__Mikroservis/Kupac__Mikroservis/Kupac__Mikroservis.sln -c Debug -o out
          dotnet publish Andjela/Zalba_Mikroservis/Zalba_Mikroservis/Zalba_Mikroservis.sln -c Debug -o out
          dotnet publish Ema/KatastarskaOpstina_MikroservisiProjekat/KatastarskaOpstina_MikroservisiProjekat.sln -c Debug -o out
          dotnet publish Ema/Parcela_MikroservisiProjekat/Parcela_MikroservisiProjekat.sln -c Debug -o out
          dotnet publish Luka/KorisnikSistema/KorisnikSistema.sln -c Debug -o out
          dotnet publish Luka/Licitacija_Project/Licitacija_Project.sln -c Debug -o out
          dotnet publish Masa/UgovorOZakupu/UgovorOZakupu.sln -c Debug -o out
          dotnet publish Masa/ZasticenaZonaMikroservis/ZasticenaZonaMikroservis.sln -c Debug -o out
          dotnet publish Pavle/JavnoNadPavle/JavnoNadPavle.sln -c Debug -o out
          dotnet publish Pavle/NadmetanjeApp/NadmetanjeApp.sln -c Debug -o out
          dotnet publish Sergej/Dokument_Sergej/Dokument_Sergej.sln -c Debug -o out
          dotnet publish Sergej/Komisija_Sergej/Komisija_Sergej.sln -c Debug -o out
          dotnet publish BoskoIspravljen/LicnostProjekat/LicnostProjekat.sln -c Debug -o out
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
